export const RACES_BY_TYPE: Record<string, string[]> = {
  Chien: [
    "Labrador",
    "Berger Allemand",
    "Golden Retriever",
    "Bulldog Français",
    "Bulldog Anglais",
    "Caniche",
    "Caniche Toy",
    "Chihuahua",
    "Husky",
    "Beagle",
    "Rottweiler",
    "Yorkshire",
    "Spitz Nain",
    "Shih Tzu",
    "Bichon Frisé",
    "Samoyède",
    "Akita",
    "Shiba Inu",
    "Border Collie",
    "Berger Australien",
    "Dalmatien",
    "Dobermann",
    "Boxer",
    "Teckel",
    "Cocker Spaniel",
    "Cavalier King Charles",
    "Malinois",
    "Saint-Bernard",
    "Terre-Neuve",
    "Lévrier Greyhound",
  ],
  Chat: [
    "Européen",
    "Siamois",
    "Persan",
    "Maine Coon",
    "British Shorthair",
    "Bengal",
    "Ragdoll",
    "Sphynx",
    "Abyssin",
    "Sacré de Birmanie",
    "Norvégien",
    "Sibérien",
    "Scottisch Fold",
    "Chartreux",
    "Angora Turc",
    "Burmese",
    "Ocicat",
    "Somali",
    "Tonkinois",
    "Devon Rex",
    "Cornish Rex",
    "Munchkin",
    "Savannah",
    "Bombay",
  ],
  Lapin: [
    "Nain",
    "Bélier",
    "Rex",
    "Angora",
    "Hollandais",
    "Géant des Flandres",
    "Lionhead",
    "Mini Lop",
    "Cottontail",
    "Californien",
    "Blanc de Hotot",
    "Fauve de Bourgogne",
    "Chinchilla",
    "Harlequin",
  ],
  Hamster: [
    "Doré",
    "Russe",
    "Roborovski",
    "Chinois",
    "Campbell",
    "Teddy Bear",
    "Européen",
    "Djungarian",
  ],
  Cochon_d_Inde: [
    "Péruvien",
    "Abyssinien",
    "Shelty",
    "Couronné",
    "Rex",
    "Teddy",
    "Texel",
    "Américain",
    "Rosette",
  ],
  Perroquet: [
    "Perruche",
    "Cacatoès",
    "Gris du Gabon",
    "Ara",
    "Inséparable",
    "Calopsitte",
    "Amazone",
    "Conure",
    "Eclectus",
    "Loricule",
    "Caïque",
    "Pionus",
  ],
  Poisson: [
    "Poisson rouge",
    "Betta",
    "Guppy",
    "Néon",
    "Scalaire",
    "Combattant",
    "Discus",
    "Koi",
    "Molly",
    "Platy",
    "Tétra",
    "Danio Zébré",
    "Cichlidé",
    "Rasbora",
    "Corydoras",
  ],
  Tortue: [
    "Hermann",
    "Grecque",
    "Sulcata",
    "Pelomedusa",
    "Floride",
    "Étoilée d'Inde",
    "Léopard",
    "Marginata",
    "Horsfield",
    "Pélomeduse",
    "Boîte d'Asie",
  ],
  Oiseau: [
    "Canari",
    "Diamant Mandarin",
    "Diamant de Gould",
    "Bengali",
    "Pinson",
    "Moineau",
    "Rossignol",
    "Verdier",
    "Chardonneret",
    "Linotte",
  ],
  Furet: [
    "Standard",
    "Angora",
    "Américain",
    "Européen",
  ],
  Reptile: [
    "Gecko Léopard",
    "Iguane Vert",
    "Dragon Barbu",
    "Caméléon",
    "Lézard Bleu",
    "Scinque",
    "Anole",
    "Boa Constricteur",
    "Python Royal",
    "Couleuvre",
  ],
};

export const PET_TYPES = Object.keys(RACES_BY_TYPE);
