export const RACES_BY_TYPE: Record<string, string[]> = {
  Chien: [
    "Labrador",
    "Berger Allemand",
    "Golden Retriever",
    "Bulldog Français",
    "Caniche",
    "Chihuahua",
    "Husky",
    "Beagle",
    "Rottweiler",
    "Yorkshire",
  ],
  Chat: [
    "Européen",
    "Siamois",
    "Persan",
    "Maine Coon",
    "British Shorthair",
    "Bengal",
    "Ragdoll",
    "Sphynx",
    "Abyssin",
    "Sacré de Birmanie",
  ],
  Lapin: [
    "Nain",
    "Bélier",
    "Rex",
    "Angora",
    "Hollandais",
    "Géant des Flandres",
  ],
  Hamster: ["Doré", "Russe", "Roborovski", "Chinois", "Campbell"],
  Cochon_d_Inde: ["Péruvien", "Abyssinien", "Shelty", "Couronné", "Rex"],
  Perroquet: [
    "Perruche",
    "Cacatoès",
    "Gris du Gabon",
    "Ara",
    "Inséparable",
    "Calopsitte",
  ],
  Poisson: [
    "Poisson rouge",
    "Betta",
    "Guppy",
    "Néon",
    "Scalaire",
    "Combattant",
  ],
  Tortue: [
    "Hermann",
    "Grecque",
    "Sulcata",
    "Pelomedusa",
    "Floride",
  ],
};

export const PET_TYPES = Object.keys(RACES_BY_TYPE);
